### ISSUE TITLE
Link Not Working

### ISSUE THREAD

**Issue by pawarbi** [deneb-viz/deneb-viz.github.io#21]
Hi Daniel, "Download this workbook" link on[ this page](https://deneb-viz.github.io/interactivity-selection#simple-worked-examples) is not working. The link is pointed to : https://deneb-viz.github.io/pbix/Deneb%20-%20Simple%20Cross-Filtering%20Examples.pbix

I couldn't find this location or the file.

Thanks

**Comment by dm-p** [comment]
Thanks, @pawarbi - that's weird, as I just navigated and clicked the link, and it downloaded fine for me.

It might be that if you visited the website prior to 1.0, the previous version (written in Gatsby) is still being served to you and the URL to the workbook has changed as the new site uses Docusaurus and hashes static assets when it's built.

[This direct URL should work](http://deneb-viz.github.io/assets/files/Deneb-Simple-Cross-Filtering-Examples-20b748abea10fa926bc2db03a293755f.pbix), but I'd appreciate if you can try shift-reloading the page (depends on browser, but whatever you would do to "hard-reload" a page and clear your current cache) and trying the link again.

Please let me know how you get on and I can investigate further if needed.

**Comment by pawarbi** [comment]
Thanks @dm-p , it's working fine on my personal laptop but not on company laptop so I am assuming it's firewalled. Appreciate you looking it up. Please close the issue. Thanks 👍

**Comment by dm-p** [comment]
Cheers for letting me know! Please feel free to re-open or comment if you spot anything else that can help assist in future.
