### ISSUE TITLE
to be added as a community expert

### ISSUE THREAD

**Issue by avatorl** [deneb-viz/deneb-viz.github.io#40]
Andrzej Leszkiewicz: https://github.com/avatorl/Deneb-Vega-Help

![Andrzej](https://github.com/deneb-viz/deneb-viz.github.io/assets/59934292/0527178a-21e6-4b79-b99a-8a3bc787c42a)

`You agree to our [Code of Conduct](https://github.com/deneb-viz/.github?tab=coc-ov-file):` Agree

**Comment by dm-p** [comment]
Thanks, @avatorl, for putting yourself forward, and to @Giammaria for preparing the PR. The changes have been approved and deployed to the support page. The cache may take a short time to update organically, but you can force this by manually refreshing the page once it has loaded.
