### ISSUE TITLE
to be added as a community expert

### ISSUE THREAD

**Issue by isinkosemen** [deneb-viz/deneb-viz.github.io#41]
Isin Kosemen
https://github.com/isinkosemen/Deneb-Vega-Vega-Lite-help/issues
I agree to the [code of conduct](https://github.com/deneb-viz/.github?tab=coc-ov-file). 
Profile photo: https://github.com/deneb-viz/deneb-viz.github.io/assets/28147353/0445e05d-2c46-47df-b0d0-6672a91694a8

**Comment by dm-p** [comment]
Thanks, @isinkosemen , for putting yourself forward, and to @Giammaria, for preparing the PR. The changes have been approved and deployed to the support page. The cache may take a short time to update organically, but you can force this by manually refreshing the page once it has loaded.
