### ISSUE TITLE
Using Vega how to set the the min yscale based on a data field.

### ISSUE THREAD

**Issue by tobytarczy** [deneb-viz/deneb-viz.github.io#52]
I have tried a few variations on this, firstly in Vega-Lite and all things started to point to Vega due the complexity of what I am trying to do. I should say I am not a coder but do know how to use ChatGPT to develop complex Power BI dashboards. 
I am developing a vertical gauge/bar visual that is unique to trading FX accounts, and for the most part I can create it using third party visual but it is not 100% so I turned to Vega in the end and have managed to create the visual and now what I would like to do is set the min y axis level to be based on a measure and data field called "MLL 8%", (Maximum Limit Loss 8%), so if I have an account that is $100k that lowest level before the account is closed is $92,000, and this should be min value or to the nearest 10,000, "90,000". This way the visual will be useable for the trader. I have tried various different techniques using Vega and Deneb which hasn't worked.   The key data fields that are being used in the visual include: "Starting Balance", "Sum of Profit Target Value", "MLL 8%", "WLL 5%", and "CumulativeBalance". I have included a screenshot of the dashboard using a third party visual which is not quite right and looks terrible, along with visual that I have created so far with Vega, I should note that this visual is per "login ID" trading account. 

I would appreciate any helping in getting the scale set to the "MLL 8%". This is dynamic as if a trader has a $25K account this different as it would be for any "Starting Balance".

![Vega Deneb Visual TT01](https://github.com/deneb-viz/deneb-viz.github.io/assets/70798915/8bd52fb7-42d8-47e8-852a-9d850962bf97)
![Traders Dashboard sample](https://github.com/deneb-viz/deneb-viz.github.io/assets/70798915/b175c0f5-54ba-4a9e-8889-9dc0e42a6abe)
![Vega visual and data](https://github.com/deneb-viz/deneb-viz.github.io/assets/70798915/d35c0fb7-a5b4-4839-873c-325e406ffc59)
[Traders Account Profile.deneb.json](https://github.com/deneb-viz/deneb-viz.github.io/files/14434562/Traders.Account.Profile.deneb.json)

I can be reached on toby.tarczy@calvella.com

Many thanks in advance

Toby Tarczy

**Comment by tobytarczy** [comment]
I am also looking to create a gradient color fill in the vertical bar where the bottom will be deep red and top will be a dark green as part of the visual.

**Comment by tobytarczy** [comment]
I think have sorted gradient colour through a video, still stuck on setting the yscale range

**Comment by dm-p** [comment]
Hi @tobytarczy, and thanks for your interest in Deneb. Just so you know, this repository tracks the development of Deneb's documentation site, and people do not monitor the issues for active support requests. [Please refer to Deneb's support page](https://deneb-viz.github.io/support) for places where you can get help from community members on language aspects.

**Comment by tobytarczy** [comment]
Thank you for your guidance.

Kind Regards,

Toby Tarczy
Calvella
+44 77991 33349

Calvella Limited, reserves the right to monitor e-mails and any replies sent back.  Registered address; Sky View, Argosy Road, East Midlands Airport, Castle Donington, Derby DE74 2SA. Registered in England and Wales, Company No. 6052142; Vat Reg. No 894273877.
